name: .NET
variables:
  buildConfiguration: Release
  buildPlatform: Any CPU
  coreSolution: 'src\Caliburn.Micro.sln'
  setupSamplesSolution: 'samples\setup\Setup.sln'
  featuresSamplesSolution: 'samples\features\Features.sln'
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019



steps:
- step: UseDotNet@2
  displayName: 'Install .NET Core 3'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- step: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool
  
- script: nbgv cloud
  displayName: Set Version

- step: VSBuild@1
  displayName: Nuget Restore
  inputs:
    solution: '$(coreSolution)'
    msbuildArgs: '/t:Restore'
    configuration: '$(buildConfiguration)'

- step: VSBuild@1
  displayName: Build & Pack Core Solution
  inputs:
    solution: '$(coreSolution)'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/t:Pack /p:JavaSdkDirectory="$(JAVA_HOME_8_X64)"'

- step: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: '**/*Test*/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- step: NuGetCommand@2
  displayName: Restore Setup Solution
  inputs:
    restoreSolution: '$(setupSamplesSolution)'

- step: VSBuild@1
  displayName: Build Setup Solution
  inputs:
    solution: '$(setupSamplesSolution)'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/t:Build /p:JavaSdkDirectory="$(JAVA_HOME_8_X64)"'

- step: NuGetCommand@2
  displayName: Restore Features Solution
  inputs:
    restoreSolution: '$(featuresSamplesSolution)'

- step: VSBuild@1
  displayName: Build Features Solution
  inputs:
    solution: '$(featuresSamplesSolution)'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/t:Build /p:JavaSdkDirectory="$(JAVA_HOME_8_X64)"'

- step: CopyFiles@2
  displayName: Copy Packages to Artifact Directory
  inputs:
    Contents: 'packages\*.nupkg'
    TargetFolder: '$(build.artifactStagingDirectory)'

- step: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: Packages
