name: .NET

  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019



    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 0


    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400
      
    - name: Setup Java SDK
      uses: actions/setup-java@v1
      with:
        java-version: 17

      
    - name: Setup NuGet.exe for use with actions
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@fd9fffd6ca4541cf4152a9565835ca1a88a6eb37
      uses: NuGet/setup-nuget@v1.1.1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: search workloads
      run: dotnet workload search
    - name: restore workloads
      run: dotnet workload install maui maui-android maui-ios maui-maccatalyst maui-windows android --source https://api.nuget.org/v3/index.json
    - name: list workloads
      run: dotnet workload list
    - name: Nerdbank.GitVersioning
      # You may pin to the exact commit or the version.
      # uses: dotnet/nbgv@49d4f35f34d895d282b99855b2e0034f8f608ba5
      uses: dotnet/nbgv@v0.4.0
    - name: Restore nuget packages
      run:  msbuild src\caliburn.micro.sln -t:restore

    - name: Build app for release
      run: msbuild src\caliburn.micro.sln /t:Build 
